Untitled Pull Request
mikkerman/BeerApp pull request #8
Opened 2023-06-05 08:43 UTC by mikkerman

2023-06-06 09:12 UTC, borisverbitckii commented on BeerApp/Sourse/Features/BarcodeScanner.swift
> +        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
В dispatchQueue не обязательно использовать weak self. Иногда даже может навредить, так что почитай про это

2023-06-06 09:16 UTC, borisverbitckii commented on BeerApp/Sourse/Features/BarcodeScanner.swift
> +    weak var delegate: BarcodeScannerViewDelegate?
Очень желательно почечать, какие приватные свойства, какие публичные методы и тд. Так легче читать

2023-06-06 09:18 UTC, borisverbitckii commented on BeerApp/Sourse/Features/BarcodeScanner.swift
> +    private var captureSession: AVCaptureSession!
Эту сессию можно сразу инициализировать прямо тут без late init

2023-06-06 09:19 UTC, borisverbitckii commented on BeerApp/Sourse/Features/BarcodeScanner.swift
> +    private var previewLayer: AVCaptureVideoPreviewLayer!
а эту через lazy var. lazy var  не потокобезопасен, но так как у нас в бекгрануде только сессия сканирует, то в нашем случае это безопасно. И сильно лучше, чем форс анврап

2023-06-06 09:21 UTC, borisverbitckii commented on BeerApp/Sourse/Infrastructure/Factories/ModuleFactory.swift
> +    func buildDescriptionModule(barcode: String) -> DescriptionViewController {
Один из этих 2 последних методов лишний

2023-06-06 09:21 UTC, borisverbitckii commented on BeerApp/Sourse/Infrastructure/Factories/ModuleFactory.swift
> +
??

2023-06-06 09:21 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Coordinator.swift
> +        print("showDescriptionWithBarcode called with barcode: \(barcode)")
Судя по всему это лучше в логер

2023-06-06 09:21 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Coordinator.swift
> +        sourceVC.present(descriptionViewController, animated: true, completion: nil)
Параметры с новой строки

2023-06-06 09:22 UTC, borisverbitckii commented on BeerApp/Sourse/Infrastructure/Factories/ModuleFactory.swift
> +
Для приватных методов есть комментарий, но нет приватных методов

2023-06-06 09:23 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraViewController.swift
> +    var scannerView: BarcodeScannerView!
Не надежные эти истории с форс анврапом. Когда класс разрастается и приходит работать другой разработчик, может выстрелить в ногу из з аэтого

2023-06-06 09:23 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraViewController.swift
> +              print(font)
Судя по всему это можно убрать

2023-06-06 09:24 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraViewController.swift
> +        scannerView = BarcodeScannerView(frame: CGRect(x: view.frame.midX - 150,
Вынести константы

2023-06-06 09:24 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraViewController.swift
> +        instructionLabel.text = "Держите штрих-код поперек красной линии"
В локализации

2023-06-06 09:24 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraViewController.swift
> +        instructionLabel.font = UIFont(name: "Montserrat-Regular", size: 16)
Специально создавали шрифты, чтобы статически уже настроенные переменные сюда подкидывать. Надо заменить

2023-06-06 09:25 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraViewController.swift
> +        print("Scanning Failed. Please try again.")
Все принты в логи

2023-06-06 09:25 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/DescriptionModule/DescriptionModuleAssembler.swift
> +        viewController.barCode = barcode
Должно передаваться в презентер. Потому что дальнейшую логику будет делать именно он, так как будет дергать инфу с сети. Надо сразу поправить

2023-06-06 09:26 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/DescriptionModule/DescriptionViewController.swift
> +    var barCode = ""
Если есть возможность инжектить переменные через инициализатор - то лучше им и воспользоваться. И сделать проперти приватным

2023-06-06 09:27 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/DescriptionModule/DescriptionViewController.swift
> +//        Наименование:
Походу это надо убирать. В этом файле, кстати, еще надо вынести все константы

2023-06-06 09:28 UTC, borisverbitckii requested changes

2023-06-06 09:28 UTC, borisverbitckii commented on BeerApp.xcodeproj/project.pbxproj
>  		C62380F229EB2EBA004B7091 /* SplashViewController.swift in Sources */ = {isa = PBXBuildFile; fileRef = C62380F129EB2EBA004B7091 /* SplashViewController.swift */; };
Пустой коммент

2023-06-07 18:17 UTC, mikkerman commented on BeerApp/Sourse/Features/BarcodeScanner.swift
> +        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
func startScanning() {
        DispatchQueue.global(qos: .userInitiated).async {
            self.captureSession.startRunning()
        }
    }

    func stopScanning() {
        DispatchQueue.global(qos: .userInitiated).async {
            self.captureSession.stopRunning()
        }
    }
    Исправил

2023-06-07 18:23 UTC, mikkerman commented on BeerApp/Sourse/Features/BarcodeScanner.swift
> +    private var captureSession: AVCaptureSession!
private var captureSession = AVCaptureSession() 
исправил

2023-06-07 18:27 UTC, mikkerman commented on BeerApp/Sourse/Features/BarcodeScanner.swift
> +    private var previewLayer: AVCaptureVideoPreviewLayer!
lazy var previewLayer: AVCaptureVideoPreviewLayer = {
        let layer = AVCaptureVideoPreviewLayer(session: captureSession)
        return layer
    }()
    
    испрвавил

2023-06-07 18:27 UTC, mikkerman commented on BeerApp/Sourse/Infrastructure/Factories/ModuleFactory.swift
> +    func buildDescriptionModule(barcode: String) -> DescriptionViewController {
исправил

2023-06-07 18:27 UTC, mikkerman commented on BeerApp/Sourse/Presentation/Coordinator.swift
> +        print("showDescriptionWithBarcode called with barcode: \(barcode)")
+

2023-06-07 18:28 UTC, mikkerman commented on BeerApp/Sourse/Presentation/Coordinator.swift
> +        sourceVC.present(descriptionViewController, animated: true, completion: nil)
Исправил

2023-06-07 18:28 UTC, mikkerman commented on BeerApp/Sourse/Infrastructure/Factories/ModuleFactory.swift
> +
Исправил

2023-06-07 18:29 UTC, mikkerman commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraViewController.swift
> +    var scannerView: BarcodeScannerView!
var scannerView = BarcodeScannerView(frame: .zero) можно использовать?

2023-06-07 18:29 UTC, mikkerman commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraViewController.swift
> +              print(font)
исправлено

2023-06-07 18:35 UTC, mikkerman commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraViewController.swift
> +        scannerView = BarcodeScannerView(frame: CGRect(x: view.frame.midX - 150,
private extension CameraViewController {
    enum LocalConstants {
        static let ellipseHeightMultiplier: CGFloat = 0.145
        static let ellipseControlPointMultiplier: CGFloat = 0.185
        static let cornerRadius: CGFloat = 10
        static let scannerViewWidthHeight: CGFloat = 300
        static let lineViewWidth: CGFloat = 250
        static let lineViewHeight: CGFloat = 1
        static let instructionLabelTopConstant: CGFloat = 30
        static let textViewLeadingTrailingConstant: CGFloat = 30
        static let labelLeadingConstant: CGFloat = 30
        static let labelTopConstant: CGFloat = 90
    }
    Исправлено

2023-06-07 18:56 UTC, mikkerman commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraViewController.swift
> +        instructionLabel.text = "Держите штрих-код поперек красной линии"
instructionLabel.text = NSLocalizedString("instructionLabelText", comment: "")
исправлено

2023-06-07 19:04 UTC, mikkerman commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraViewController.swift
> +        instructionLabel.font = UIFont(name: "Montserrat-Regular", size: 16)
Исправлено

2023-06-07 19:09 UTC, mikkerman commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraViewController.swift
> +        print("Scanning Failed. Please try again.")
исправил, только появляется ошибка при внесении этого принта в лог 
print("Barcode: ", str ?? "No barcode")

2023-06-08 18:30 UTC, mikkerman commented on BeerApp/Sourse/Features/BarcodeScanner.swift
> +    weak var delegate: BarcodeScannerViewDelegate?
Добавил MARK

2023-06-08 19:08 UTC, mikkerman commented on BeerApp/Sourse/Presentation/Modules/DescriptionModule/DescriptionModuleAssembler.swift
> +        viewController.barCode = barcode
Вроде исправил

2023-06-08 19:16 UTC, mikkerman commented on BeerApp/Sourse/Presentation/Modules/DescriptionModule/DescriptionViewController.swift
> +    var barCode = ""
Тоже вроде исправил

2023-06-08 19:17 UTC, mikkerman commented on BeerApp/Sourse/Presentation/Modules/DescriptionModule/DescriptionViewController.swift
> +//        Наименование:
можно убрать все и вынести в константы когда получу данные с апи?

2023-06-09 05:44 UTC, borisverbitckii commented on BeerApp/Resource/Localizable.strings
> +"instructionLabelText" = "Держите штрих-код поперек красной линии";
Все заголовки с экрана описания тоже должны быть здесь, например, "название" пива и тд

2023-06-09 05:44 UTC, borisverbitckii commented on BeerApp/Sourse/Features/BarcodeScanner.swift
> +    private var captureSession = AVCaptureSession()
Желательно перед любым блоком с MARK делать отступ, а то все в одну кашу.

2023-06-09 05:48 UTC, borisverbitckii commented on BeerApp/Sourse/Features/BarcodeScanner.swift
> +        let layer = AVCaptureVideoPreviewLayer(session: captureSession)
В целом можно было сразу напрямую инициализировать, это вкусовщина, так что и так норм

2023-06-09 05:49 UTC, borisverbitckii commented on BeerApp/Sourse/Infrastructure/Factories/ModuleFactory.swift
> +    func buildDescriptionModuleWithBarcode(_ barcode: String, coordinator: Coordinator) -> UIViewController {
С новых строк параметры. Кстати, в xcode 15 даже сделали в меню рефакторинга автоматический перенос параметров на новую строку. Лучше в этом за собой следить, потому что потом проект растет и приятнее его читать

2023-06-09 05:52 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraAssembler.swift
> +        let viewController = CameraViewController(coordinator: coordinator)
Можно сразу return CameraViewController(coordinator: coordinator)

2023-06-09 05:54 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraViewController.swift
> +    var coordinator: Coordinator
По канонам лучше чтобы MVP паттерн соблядался, чтобы навигация и результаты сканирования передавались оттуда. В один контроллер можно, это проблем нет. Но так как это выставочный проект,  то лучше такие вещи соблюдать

2023-06-09 05:56 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraViewController.swift
> +        instructionLabel.text = NSLocalizedString("instructionLabelText", comment: "")
Не не не, у нас должен быть enum Strings где как раз дергаются все переменные из локализаций. Важно, чтобы любые параметры, которые устанавливаются с помощью строки были не в боевом коде, а где-то вынесены. Чтобы нельзя было допустить ошибку, а в строке это сделать проще всего

2023-06-09 05:56 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraViewController.swift
> +        label.text = "BeerApp"
Тоже надо выносить куда-то

2023-06-09 05:57 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/DescriptionModule/DescriptionPresenter.swift
> +    init(coordinator: Coordinator, barcode: String) {
С новых строк

2023-06-09 05:58 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/DescriptionModule/DescriptionViewController.swift
> +    private(set) var barcode = ""
У тебя штрих код попадает и в презентер и сюда, но должен быть в презентере

2023-06-09 05:59 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/DescriptionModule/DescriptionViewController.swift
> +    func setBarcode(_ barcode: String) {
Раз штрихкод в презентере, то этот метод не нужен

2023-06-09 06:02 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/DescriptionModule/DescriptionViewController.swift
> +//        Guinness Draught
Надо убрать, раз закомментировано. Заголовки для секций должны быть в локализации. А все остальное (значения) в модели данных, которая даже если моковая - должна быть в презентере. Потому что потом из сети мы будем эти данные туда получать

2023-06-09 06:03 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/Splash/SplashPresenter.swift
> +    func pushSplash(with view: SplashViewProtocol) {
Наверно имелось в виду attack а не push

2023-06-09 06:24 UTC, borisverbitckii requested changes

2023-06-09 06:24 UTC, borisverbitckii commented on BeerApp.xcodeproj/project.pbxproj
>  		C62380F229EB2EBA004B7091 /* SplashViewController.swift in Sources */ = {isa = PBXBuildFile; fileRef = C62380F129EB2EBA004B7091 /* SplashViewController.swift */; };
пустой коммент

2023-06-09 07:04 UTC, borisverbitckii commented on BeerApp/Sourse/Features/BarcodeScanner.swift
> +        let layer = AVCaptureVideoPreviewLayer(session: captureSession)
у тебя кстати ниже previewLayer вотрой раз иициализируется

2023-06-09 07:12 UTC, borisverbitckii requested changes

2023-06-09 07:12 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraViewController.swift
> +        scannerView = BarcodeScannerView()
У тебя сверху вью уже инициализирована

2023-06-09 07:12 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraViewController.swift
> +    private func setupScannerView() {
Название метода не верное, так как настраивается тут все

2023-06-10 15:49 UTC, mikkerman commented on BeerApp/Sourse/Features/BarcodeScanner.swift
> +    private var captureSession = AVCaptureSession()
Исправил

2023-06-10 15:54 UTC, mikkerman commented on BeerApp/Sourse/Features/BarcodeScanner.swift
> +        let layer = AVCaptureVideoPreviewLayer(session: captureSession)
Удалил инициализацию из метода

2023-06-10 16:00 UTC, mikkerman commented on BeerApp/Sourse/Infrastructure/Factories/ModuleFactory.swift
> +    func buildDescriptionModuleWithBarcode(_ barcode: String, coordinator: Coordinator) -> UIViewController {
исправил

2023-06-10 16:01 UTC, mikkerman commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraAssembler.swift
> +        let viewController = CameraViewController(coordinator: coordinator)
исправил

2023-06-10 16:03 UTC, mikkerman commented on BeerApp/Sourse/Presentation/Modules/DescriptionModule/DescriptionPresenter.swift
> +    init(coordinator: Coordinator, barcode: String) {
Исправил

2023-06-13 09:20 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraViewController.swift
> +         scannerView.layer.cornerRadius = 10
Не вынес

2023-06-13 09:20 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraViewController.swift
> +        print("Barcode: ", str ?? "No barcode")
В логгер

2023-06-13 09:20 UTC, borisverbitckii commented on BeerApp/Sourse/Presentation/Modules/CameraModule/CameraViewController.swift
> +        print("Scanning stopped")
В логгер

2023-06-13 10:00 UTC, borisverbitckii requested changes

2023-06-13 10:00 UTC, borisverbitckii commented on BeerApp.xcodeproj/project.pbxproj
>  		C62380F229EB2EBA004B7091 /* SplashViewController.swift in Sources */ = {isa = PBXBuildFile; fileRef = C62380F129EB2EBA004B7091 /* SplashViewController.swift */; };
Коммент чтобы поменять статус пра

2023-06-18 19:14 UTC, merged